name: Package and release

on:
  push:
    tags:
      - '**'

jobs:
  
  release:

    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      # "GITHUB_TOKEN" is a secret automatically provided to the workflow
      # for your own token, the name cannot start with "GITHUB_"
    
    steps:

      - name: Clone project
        uses: actions/checkout@v3
      
      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -g retail
